### ISSUE TITLE
TypeError: undefined is not a function at Array.find (<anonymous>)

### ISSUE THREAD

**Issue by korggy** [vuetifyjs/vuetify-loader#167]
Just updated to v1.7.0 & webpack 5.15.0. Received the following error upon `yarn serve`:

`
PS D:\Visual Studio Projects\Taskly.client> yarn serve
yarn run v1.22.10
warning ..\..\package.json: No license field
$ vue-cli-service serve
 INFO  Starting development server...
 ERROR  TypeError: undefined is not a function
TypeError: undefined is not a function
    at Array.find (<anonymous>)
    at D:\Visual Studio Projects\Taskly.client\node_modules\vuetify-loader\lib\getVueRules.js:19:49
    at Array.map (<anonymous>)
    at getVueRules (D:\Visual Studio Projects\Taskly.client\node_modules\vuetify-loader\lib\getVueRules.js:19:11)
    at VuetifyLoaderPlugin.apply (D:\Visual Studio Projects\Taskly.client\node_modules\vuetify-loader\lib\plugin.js:12:22)
    at webpack (D:\Visual Studio Projects\Taskly.client\node_modules\@vue\cli-service\node_modules\webpack\lib\webpack.js:51:13)
    at serve (D:\Visual Studio Projects\Taskly.client\node_modules\@vue\cli-service\lib\commands\serve.js:163:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by rti** [comment]
@korggy I just found a workaround which works for me... :)
If you want to give it a try, you will find the branch here https://github.com/rti/vuetify-loader/tree/fix_isVueLoader_undefined
