### ISSUE TITLE
Error with webpack and script setup

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify-loader#199]
When doing a production webpack build, I see:

```
(node:9032) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at D:\Programming\Projects\x\v4\front-end\node_modules\vuetify-loader\dist\loader.js:9:77
    at new Promise (<anonymous>)
    at Object.VuetifyLoader (D:\Programming\Projects\x\v4\front-end\node_modules\vuetify-loader\dist\loader.js:8:9)
    at LOADER_EXECUTION (D:\Programming\Projects\x\v4\front-end\node_modules\loader-runner\lib\LoaderRunner.js:132:14)
    at runSyncOrAsync (D:\Programming\Projects\x\v4\front-end\node_modules\loader-runner\lib\LoaderRunner.js:133:4)
    at iterateNormalLoaders (D:\Programming\Projects\x\v4\front-end\node_modules\loader-runner\lib\LoaderRunner.js:250:2)
    at iterateNormalLoaders (D:\Programming\Projects\x\v4\front-end\node_modules\loader-runner\lib\LoaderRunner.js:239:10)
    at D:\Programming\Projects\x\v4\front-end\node_modules\loader-runner\lib\LoaderRunner.js:254:3
    at runSyncOrAsync (D:\Programming\Projects\x\v4\front-end\node_modules\loader-runner\lib\LoaderRunner.js:143:11)
    at iterateNormalLoaders (D:\Programming\Projects\x\v4\front-end\node_modules\loader-runner\lib\LoaderRunner.js:250:2)
```

The issue is here: https://github.com/vuetifyjs/vuetify-loader/blob/4253e7b7224393adae8a5bccec650d70fb8a9cde/packages/vuetify-loader/src/loader.ts#L10

`content` is:

```
import script from "./app.vue?vue&type=script&lang=ts&setup=true"
export * from "./app.vue?vue&type=script&lang=ts&setup=true"

export default script
```

The project uses TS and script setup.

**Comment by glen-84** [comment]
These changes appear to fix the issue*, but I don't know if you planned to do more extensive refactoring.

```diff
- this.loadModule(/^import { render } from "(.+)"$/m.exec(content)![1], (err, source) => {
+ this.loadModule(/^import (?:{ render }|script) from "(.+)"$/m.exec(content)![1], (err, source) => {
```

```diff
- this.loadModule(/^export \* from "(.+)"$/.exec(source)[1], (err, source) => {
+ this.loadModule(/export \* from "(.+)"$/.exec(source)[1], (err, source) => {
```

`source` is:

> export { default } from "-!../../node_modules/ts-loader/index.js??clonedRuleSet-5.use[0]!../../node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./app.vue?vue&type=script&lang=ts&setup=true"; export * from "-!../../node_modules/ts-loader/index.js??clonedRuleSet-5.use[0]!../../node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./app.vue?vue&type=script&lang=ts&setup=true"

`*` I haven't tested _without_ script-setup, but it should be fine.
