### ISSUE TITLE
[@vuetify/vite-plugin] Unable to override variables

### ISSUE THREAD

**Issue by lukeromanowicz** [vuetifyjs/vuetify-loader#203]
When using vite-plugin 1.0.0-alpha.3 with vuetify 3.0.0-alpha.11 and trying to override any variables, I am getting:
```
 Internal server error: This variable was not declared with !default in the @used module.
 ```
 
 For instance when you test it on the setup in dev package, you'll get:
 ```
$> yarn dev:vite 
yarn run v1.22.11
$ vite
Pre-bundling dependencies:
  vue
  vuetify
(this will be run only when your dependencies or config have changed)
Port 3000 is in use, trying another one...
Port 3001 is in use, trying another one...

  vite v2.5.1 dev server running at:

  > Local: http://localhost:3002/
  > Network: use `--host` to expose

  ready in 243ms.

10:51:05 AM [vite] new dependencies found: @vuetify/loader-shared/runtime, vuetify/lib/components/VAlert/index.mjs, vuetify/lib/components/VApp/index.mjs, vuetify/lib/components/VBtn/index.mjs, vuetify/lib/components/VCard/index.mjs, vuetify/lib/components/VGrid/index.mjs, vuetify/lib/components/VImg/index.mjs, vuetify/lib/components/VTextField/index.mjs, vuetify/lib/directives/index.mjs, updating...
10:51:05 AM [vite] ✨ dependencies updated, reloading page...
10:51:06 AM [vite] Internal server error: This variable was not declared with !default in the @used module.
  ╷
3 │   $alert-padding: 24px,
  │   ^^^^^^^^^^^^^^^^^^^^
  ╵
  src/main.scss 3:3  root stylesheet
  Plugin: vite:css
  File: /tmp/vuetify-loader/dev/src/main.scss
  Error: This variable was not declared with !default in the @used module.
    ╷
  3 │   $alert-padding: 24px,
    │   ^^^^^^^^^^^^^^^^^^^^
    ╵
    src/main.scss 3:3  root stylesheet
      at Object._newRenderError (/tmp/vuetify-loader/node_modules/sass/sass.dart.js:13319:19)
      at Object._wrapException (/tmp/vuetify-loader/node_modules/sass/sass.dart.js:13139:16)
      at _render_closure1.call$2 (/tmp/vuetify-loader/node_modules/sass/sass.dart.js:82377:21)
      at _RootZone.runBinary$3$3 (/tmp/vuetify-loader/node_modules/sass/sass.dart.js:27674:18)
      at _FutureListener.handleError$1 (/tmp/vuetify-loader/node_modules/sass/sass.dart.js:26223:19)
      at _Future__propagateToListeners_handleError.call$0 (/tmp/vuetify-loader/node_modules/sass/sass.dart.js:26521:49)
      at Object._Future__propagateToListeners (/tmp/vuetify-loader/node_modules/sass/sass.dart.js:4546:77)
      at _Future._completeError$2 (/tmp/vuetify-loader/node_modules/sass/sass.dart.js:26353:9)
      at _AsyncAwaitCompleter.completeError$2 (/tmp/vuetify-loader/node_modules/sass/sass.dart.js:26007:12)
      at Object._asyncRethrow (/tmp/vuetify-loader/node_modules/sass/sass.dart.js:4345:17)

```

**Comment by lukeromanowicz** [comment]
Looks like `$alert-padding` is not supported. Other variables work fine
