### ISSUE TITLE
SassError: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify-loader#205]
```
ERROR in ./app/core/plugins/main.scss
Module build failed (from ../../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
2 │ @forward 'D:\Programming\Projects\x\v4\front-end\node_modules\vuetify\lib\components\VApp\VApp.sass';
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\.cache\vuetify\styles.scss 2:1  @use
  src\app\core\plugins\main.scss 1:1           root stylesheet
    at processResult (D:\Programming\Projects\x\v4\front-end\node_modules\webpack\lib\NormalModule.js:721:19)
    at D:\Programming\Projects\x\v4\front-end\node_modules\webpack\lib\NormalModule.js:827:5
    at D:\Programming\Projects\x\v4\front-end\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\Programming\Projects\x\v4\front-end\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (D:\Programming\Projects\x\v4\front-end\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at D:\Programming\Projects\x\v4\front-end\node_modules\sass-loader\dist\index.js:54:7
    at Function.call$2 (D:\Programming\Projects\x\v4\front-end\node_modules\sass\sass.dart.js:93852:16)
    at _render_closure.call$0 (D:\Programming\Projects\x\v4\front-end\node_modules\sass\sass.dart.js:82146:23)
    at Object.Primitives_applyFunction (D:\Programming\Projects\x\v4\front-end\node_modules\sass\sass.dart.js:6502:30)
    at Object.Function_apply (D:\Programming\Projects\x\v4\front-end\node_modules\sass\sass.dart.js:13832:16)
 @ ./app/core/plugins/vuetify.ts 2:0-21
 @ ./main.ts 7:0-53 11:75-82
 ```

Looks like more fun with Windows paths. 🙃

(back slashes should be escaped, or replaced with forward slashes)

**Comment by glen-84** [comment]
@KaelWD, is there anything that I can do to help with this? I'm on Discord if you need me to test something.
