### ISSUE TITLE
vuetify:styles plugin fails in production building

### ISSUE THREAD

**Issue by lukeromanowicz** [vuetifyjs/vuetify-loader#213]
When building vite project, I am getting vuetify:styles error

```
> dashboard-frontend@0.0.0 build /tmp/frontend
> vite build

vite v2.6.7 building for production...
✓ 510 modules transformed.
[vuetify:styles] Cannot read property 'moduleGraph' of undefined
file: /tmp/frontend/src/styles/vuetify.scss
error during build:
TypeError: Cannot read property 'moduleGraph' of undefined
    at awaitResolve (/tmp/frontend/node_modules/@vuetify/vite-plugin/dist/stylesPlugin.js:49:24)
    at async Object.transform (/tmp/frontend/node_modules/@vuetify/vite-plugin/dist/stylesPlugin.js:92:17)
    at async ModuleLoader.addModuleSource (/tmp/frontend/node_modules/rollup/dist/shared/rollup.js:22105:30)
    at async ModuleLoader.fetchModule (/tmp/frontend/node_modules/rollup/dist/shared/rollup.js:22158:9)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/tmp/frontend/node_modules/rollup/dist/shared/rollup.js:22193:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/tmp/frontend/node_modules/rollup/dist/shared/rollup.js:22169:9)
    at async Promise.all (index 1)
    at async ModuleLoader.fetchStaticDependencies (/tmp/frontend/node_modules/rollup/dist/shared/rollup.js:22193:34)
 ```

According to the vite docs, configureServer hook is not executed in production build, only dev mode

![image](https://user-images.githubusercontent.com/46789227/137304037-69a6b889-b369-48bc-b27a-c5e829231459.png)

vite 2.6.7
vite vuetify plugin 1.0.0-alpha.5
Ubuntu 20.04
Node 14 LTS

vite config:
```
  plugins: [
    vue(),
    vuetify({ autoImport: false, styles: 'expose' }),
  ],
  ```

**Comment by BreizhReloaded** [comment]
I'm happy you mention that, I'm facing the same issue, on both Windows and WSL. Reproducible on my [Vite + Vue + Vuetity demo project](https://github.com/BreizhReloaded/my-vue-app).
