### ISSUE TITLE
vite-plugin doesn't generate source maps

### ISSUE THREAD

**Issue by ffxsam** [vuetifyjs/vuetify-loader#233]
In a Vite project using Vuetify 3.0 beta (added to proj via `vue add vuetify`), building the project doesn't generate source maps for .vue files.

Upon running `yarn build`, I get this output:

```
vite v2.8.6 building for production...
✓ 116 modules transformed.
rendering chunks (3)...Sourcemap is likely to be incorrect: a plugin (vuetify:import) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vuetify:import) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
dist/assets/logo.756d19f4.svg                            0.53 KiB
dist/assets/materialdesignicons-webfont.9bdfaf27.eot     1002.34 KiB
(etc.)
```

And in the .map files, I can see none of the code from the .vue files is present.

**Comment by JiPaix** [comment]
same problem, same message.
```
rendering chunks (2)...Sourcemap is likely to be incorrect: a plugin (vuetify:import) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vuetify:import) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vuetify:import) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```
then electron builder throws
```
[vite:build-html] The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../D:\a\AMR\AMR\packages\renderer\index.html".

error during build:
Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../D:\a\AMR\AMR\packages\renderer\index.html".
    at error (D:\a\AMR\AMR\node_modules\rollup\dist\shared\rollup.js:158:30)
    at FileEmitter.emitFile (D:\a\AMR\AMR\node_modules\rollup\dist\shared\rollup.js:15496:24)
    at Object.generateBundle (D:\a\AMR\AMR\node_modules\vite\dist\node\chunks\dep-9c153[81](https://github.com/JiPaix/AMR/runs/5616520414?check_suite_focus=true#step:6:81)6.js:21691:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
child_process.js:674
    throw err;
    ^
```
