### ISSUE TITLE
Unexpected token import (using nuxt programatically)

### ISSUE THREAD

**Issue by P4sca1** [vuetifyjs/vuetify-loader#24]
**Environment:**
`nuxt.js 2.2.0` used programatically with a `koa` web server written in `typescript`.

I just switched from importing any component on every page to using `vuetify-loader`.
When loading the page I get the following error:

```
[Node] [13:56:35] /Users/pascal/code/web/node_modules/vuetify/lib/index.js:1
[Node] (function (exports, require, module, __filename, __dirname) { import Vuetify from './components/Vuetify';
[Node] ^^^^^^
[Node]
[Node] SyntaxError: Unexpected token import
[Node] at createScript (vm.js:80:10)
[Node] at Object.runInThisContext (vm.js:152:10)
[Node] at Module._compile (module.js:605:28)
[Node] at Object.Module._extensions..js (module.js:652:10)
[Node] at Module.load (module.js:560:32)
[Node] at tryModuleLoad (module.js:503:12)
[Node] at Function.Module._load (module.js:495:3)
[Node] at Module.require (module.js:585:17)
[Node] at require (internal/module.js:11:18)
[Node] at r (/Users/pascal/code/web/node_modules/vue-server-renderer/build.js:8341:16)
[Node] at Object.vuetify/lib (server-bundle.js:5229:18)
[Node] at __webpack_require__ (server-bundle.js:27:30)
[Node] at Module../layouts/error.vue (server-bundle.js:2394:69)
[Node] at __webpack_require__ (server-bundle.js:27:30)
[Node] at Module../.nuxt/index.js (server-bundle.js:772:76)
[Node] at __webpack_require__ (server-bundle.js:27:30)
```

Relevant web server part:
```
import * as Koa from 'koa'
import config from './helpers/config'

// We are requiring these, because of missing type declarations.
const { Nuxt, Builder } = require('nuxt')
const nuxtConfig = require('../../nuxt.config')

class NuxtHelper {
	static async init(app: Koa) {
		// Instantiate nuxt.js
		app.context.nuxt = new Nuxt(nuxtConfig)

		// Enable live build & reloading on dev
		if (app.context.nuxt.options.dev && !config.disableNuxtBuilder) {
			const builder = new Builder(app.context.nuxt)
			await builder.build()
		}
	}

	static render() {
		return async (ctx: Koa.Context, next: () => Promise<any>) => {
			await next()

			ctx.status = 200 // Koa defaults to 404 when the status is unset
			ctx.req.session = ctx.session // Bind session to req for nuxt to read.

			await new Promise((resolve, reject) => {
				ctx.res.on('close', resolve) 
				ctx.res.on('finish', resolve)

				ctx.nuxt.render(ctx.req, ctx.res, (promise: Promise<any>) => {
					promise.then(resolve).catch(reject)
				})
			})
		}
	}
}

export default NuxtHelper
```

Relevant part of nuxt.config.js:
```
// We are not using es6 module syntax here, because we are using nuxt.js programatically, requiring the nuxt.config.js as a commonjs module.

const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')

module.exports = {
	dev:  (process.env.NODE_ENV !== 'production'),

	build:  {
		parallel: true,
		plugins: [
			new VuetifyLoaderPlugin(),
		],
		babel: {
			plugins: [
				["transform-imports", {
					// Enable tree shaking for vuetify components
					"vuetify": {
						transform: "vuetify/es5/components/${member}"
					}
				}]
			]
		}
	},
	...
}
```

I guess it is something with mixing `require` and `import`, but I don't know exactly.
Do you have any idea on how I can use the loader in this environment?

**Comment by KaelWD** [comment]
You need to tell nuxt to transpile vuetify: https://nuxtjs.org/api/configuration-build/#transpile
You should also remove the transform-imports plugin, that was for vuetify <=1.2

**Comment by P4sca1** [comment]
Perfect, that worked. Thank you!

For everyone who is curious, this is the changed part in nuxt.config.js:
``` 
build:  {
	parallel: true,
	plugins: [
		new VuetifyLoaderPlugin(),
	],
	transpile: [/^vuetify/]
}
```
