### ISSUE TITLE
Latest alpha version will not install. (1.0.0-alpha.13)

### ISSUE THREAD

**Issue by ktiedt** [vuetifyjs/vuetify-loader#261]
Note: Previous version (1.0.0-alpha.12) installs fine.
```
➜  my-vuetify-app npm i -D vite-plugin-vuetify
npm ERR! Cannot read properties of null (reading 'explain')

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ktiedt/.npm/_logs/2022-07-23T19_57_23_976Z-debug-0.log
```

And the log file:
```
0 verbose cli /Users/ktiedt/.nvm/versions/node/v16.16.0/bin/node /Users/ktiedt/.nvm/versions/node/v16.16.0/bin/npm
1 info using npm@8.11.0
2 info using node@v16.16.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/ktiedt/.nvm/versions/node/v16.16.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/ktiedt/2021/my-vuetify-app/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/Users/ktiedt/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/ktiedt/.nvm/versions/node/v16.16.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 timing npm:load:configload Completed in 11ms
20 timing npm:load:mkdirpcache Completed in 4ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm i vite-plugin-vuetify
23 verbose argv "i" "--save-dev" "vite-plugin-vuetify"
24 timing npm:load:setTitle Completed in 19ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:/Users/ktiedt/.npm/_logs
28 verbose logfile /Users/ktiedt/.npm/_logs/2022-07-23T19_58_45_030Z-debug-0.log
29 timing npm:load:logFile Completed in 5ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 43ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 81ms
37 timing idealTree:userRequests Completed in 3ms
38 silly idealTree buildDeps
39 silly fetch manifest vite-plugin-vuetify@^1.0.0-alpha.0
40 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
41 http fetch GET 200 https://registry.npmjs.org/vite-plugin-vuetify 66ms (cache hit)
42 silly fetch manifest vite@^2.9.9
43 http fetch GET 200 https://registry.npmjs.org/vite 10ms (cache hit)
44 silly fetch manifest less@*
45 http fetch GET 200 https://registry.npmjs.org/less 5ms (cache hit)
46 silly fetch manifest sass@*
47 http fetch GET 200 https://registry.npmjs.org/sass 6ms (cache hit)
48 silly fetch manifest stylus@*
49 http fetch GET 200 https://registry.npmjs.org/stylus 6ms (cache hit)
50 silly fetch manifest vuetify@^3.0.0-beta.0
51 http fetch GET 200 https://registry.npmjs.org/vuetify 6ms (cache hit)
52 silly fetch manifest @formatjs/intl@^1.0.0 || ^2.0.0
53 http fetch GET 200 https://registry.npmjs.org/@formatjs%2fintl 4ms (cache hit)
54 silly fetch manifest typescript@^4.5
55 http fetch GET 200 https://registry.npmjs.org/typescript 17ms (cache hit)
56 silly fetch manifest vite-plugin-vuetify@1.0.0-alpha.12
57 silly fetch manifest vite@^2.7.0
58 silly fetch manifest vuetify@^3.0.0-beta.4
59 silly fetch manifest vue@^3.2.0
60 http fetch GET 200 https://registry.npmjs.org/vue 10ms (cache hit)
61 silly fetch manifest vue-i18n@^9.0.0
62 http fetch GET 200 https://registry.npmjs.org/vue-i18n 10ms (cache hit)
63 silly fetch manifest webpack-plugin-vuetify@2.0.0-alpha.11
64 http fetch GET 200 https://registry.npmjs.org/webpack-plugin-vuetify 4ms (cache hit)
65 silly fetch manifest @vue/compiler-sfc@^3.2.6
66 http fetch GET 200 https://registry.npmjs.org/@vue%2fcompiler-sfc 4ms (cache hit)
67 silly fetch manifest webpack@^5.0.0
68 http fetch GET 200 https://registry.npmjs.org/webpack 8ms (cache hit)
69 silly fetch manifest vue@^3.2.25
70 timing idealTree Completed in 391ms
71 timing command:i Completed in 403ms
72 verbose stack TypeError: Cannot read properties of null (reading 'explain')
72 verbose stack     at Arborist.[explainPeerConflict] (/Users/ktiedt/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1434:29)
72 verbose stack     at Arborist.[failPeerConflict] (/Users/ktiedt/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1427:44)
72 verbose stack     at Arborist.[loadPeerSet] (/Users/ktiedt/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1394:34)
72 verbose stack     at async Arborist.[buildDepStep] (/Users/ktiedt/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:976:11)
72 verbose stack     at async Arborist.buildIdealTree (/Users/ktiedt/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
72 verbose stack     at async Promise.all (index 1)
72 verbose stack     at async Arborist.reify (/Users/ktiedt/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
72 verbose stack     at async Install.exec (/Users/ktiedt/.nvm/versions/node/v16.16.0/lib/node_modules/npm/lib/commands/install.js:156:5)
72 verbose stack     at async module.exports (/Users/ktiedt/.nvm/versions/node/v16.16.0/lib/node_modules/npm/lib/cli.js:78:5)
73 verbose cwd /Users/ktiedt/2021/my-vuetify-app
74 verbose Darwin 21.6.0
75 verbose node v16.16.0
76 verbose npm  v8.11.0
77 error Cannot read properties of null (reading 'explain')
78 verbose exit 1
79 timing npm Completed in 503ms
80 verbose unfinished npm timer reify 1658606325125
81 verbose unfinished npm timer reify:loadTrees 1658606325133
82 verbose unfinished npm timer idealTree:buildDeps 1658606325218
83 verbose unfinished npm timer idealTree:#root 1658606325218
84 verbose code 1
85 error A complete log of this run can be found in:
85 error     /Users/ktiedt/.npm/_logs/2022-07-23T19_58_45_030Z-debug-0.log
```

**Comment by samehdoush** [comment]
I have the same issue

**Comment by KaelWD** [comment]
> `TypeError: Cannot read properties of null (reading 'explain')`

This error is coming from npm itself.

**Comment by ktiedt** [comment]
> > `TypeError: Cannot read properties of null (reading 'explain')`
> 
> This error is coming from npm itself. 

Yet it only affects this specific version which implies there's something amiss in this latest release package.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/commit/e9ab9166ee8ed1fb0a6e77e442354d89400bb43d

**Comment by ggedde** [comment]
I was having the same issue. I switched over to yarn and everything seemed to work.
