### ISSUE TITLE
npm install vuetify-loader error 

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify-loader#277]
I am getting `fatal error: 'vips/vips8' ` when trying to install vuetify-loader

 ```
npm install vuetify-loader 
```
I got the following error 
```
contents is empty (no object file members in the library define global symbols)
npm ERR! ../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
npm ERR! #include <vips/vips8>
npm ERR!          ^~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sharp-darwin-x64/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/mtermo049/Documents/projects/ace-dewey-ui3/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/mtermo049/Documents/projects/ace-dewey-ui3/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/mtermo049/Documents/projects/ace-dewey-ui3/node_modules/sharp

```

I am running this for 
* npm 9.1.3
* Node 14.17.3
* @vue/cli 4.5.13

**Comment by KaelWD** [comment]
https://github.com/lovell/sharp/issues/2460
