### ISSUE TITLE
Error "@use rules must be written before any other rules."

### ISSUE THREAD

**Issue by reblevins** [vuetifyjs/vuetify-loader#306]
I have been trying to use sass variables with Vuetify following the instructions [here](https://www.npmjs.com/package/vite-plugin-vuetify) and [here](https://vuetifyjs.com/en/features/sass-variables/), but so far have not been successful.

I am constantly getting the following error:
```
9:27:39 AM [vite] Internal server error: @use rules must be written before any other rules.
  ╷
3 │ @use "/Users/.../dev/.../vue-app/src/vuetify-settings.scss"
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  plugin-vuetify:components/VCard/VCard.sass 3:1  root stylesheet
  Plugin: vite:css
  File: /Users/.../dev/.../vue-app/plugin-vuetify:components/VCard/VCard.sass
  Error: @use rules must be written before any other rules.
    ╷
  3 │ @use "/Users/.../dev/.../vue-app/src/vuetify-settings.scss"
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    plugin-vuetify:components/VCard/VCard.sass 3:1  root stylesheet
      at Object.wrapException (/Users/.../dev/.../vue-app/node_modules/sass/sass.dart.js:1237:17)
      at SassParser0.error$3 (/Users/.../dev/.../vue-app/node_modules/sass/sass.dart.js:92410:17)
      at SassParser0.error$2 (/Users/.../dev/.../vue-app/node_modules/sass/sass.dart.js:92415:19)
      at SassParser0.atRule$2$root (/Users/.../dev/.../vue-app/node_modules/sass/sass.dart.js:97142:19)
      at SassParser0._stylesheet0$_statement$1$root (/Users/.../dev/.../vue-app/node_modules/sass/sass.dart.js:96729:24)
      at StylesheetParser_parse__closure1.call$0 (/Users/.../dev/.../vue-app/node_modules/sass/sass.dart.js:100003:17)
      at SassParser0._sass0$_child$1 (/Users/.../dev/.../vue-app/node_modules/sass/sass.dart.js:93149:24)
      at SassParser0.statements$1 (/Users/.../dev/.../vue-app/node_modules/sass/sass.dart.js:93122:22)
      at StylesheetParser_parse_closure0.call$0 (/Users/.../dev/.../vue-app/node_modules/sass/sass.dart.js:99986:23)
      at SassParser0.wrapSpanFormatException$1$1 (/Users/.../dev/.../vue-app/node_modules/sass/sass.dart.js:92441:25)
```

My `vite.config.js` file:
```
import vue from '@vitejs/plugin-vue'
import vuetify from 'vite-plugin-vuetify'
...

export default ({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')

  return defineConfig({
    ...
    plugins: [
      vue({
        template: { transformAssetUrls }
      }),
      vuetify({ styles: { configFile: 'src/vuetify-settings.scss' } }),
    ]
    ...
  })
}
```

`src/plugins/vuetify.js`:
```
import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import 'material-design-icons-iconfont/dist/material-design-icons.css'
import 'material-symbols';
import { aliases, mso } from 'src/iconsets/mso'

const customTheme = {
  dark: false,
  colors: {
    background: '#FFFFFF',
    surface: '#FFFFFF',
    primary: '#001749',
    'primary-darken-1': '#00133D',
    'grey-darken-1': '#5B5B5B',
    secondary: '#00D86C',
    error: '#E4000F',
    info: '#2196F3',
    success: '#4CAF50',
    warning: '#FB8C00',
  },
}

export default createVuetify({
  components,
  directives,
  theme: {
    defaultTheme: 'customTheme',
    themes: {
      customTheme,
    },
  },
  icons: {
    defaultSet: 'mso',
    aliases,
    sets: {
      mso,
    },
  },
})
```

`src/vuetify-settings.scss`:
```
@use 'vuetify/settings' with (
  $color-pack: false,
  $button-border-radius: 3px
);
```

Any help would be greatly appreciated!

**Comment by KaelWD** [comment]
> `3 │ @use "/Users/.../dev/.../vue-app/src/vuetify-settings.scss"`

That's normally on line 2, I'm guessing you have prependData or something else modifying sass files?

**Comment by KaelWD** [comment]
Not sure. You can use https://www.npmjs.com/package/vite-plugin-inspect to see what the rest of the file contains.
