### ISSUE TITLE
pug compatibility broken by v1.0.7

### ISSUE THREAD

**Issue by ledermann** [vuetifyjs/vuetify-loader#32]
After upgrading vuetify-loader to 1.0.7 my app (using pug templates) is broken. Webpack fails with this error message:

```
(node:90991) UnhandledPromiseRejectionWarning: Error: Module "pug" required by "vuetify-loader" not found. Please run: npm install pug@'^2.0.0' --save
    at realRequire (/Users/ledermann/Projects/myapp/node_modules/codependency/index.js:146:9)
    at requirePeer (/Users/ledermann/Projects/myapp/node_modules/codependency/index.js:326:10)
    at Object.module.exports (/Users/ledermann/Projects/myapp/node_modules/vuetify-loader/lib/loader.js:43:21)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:90991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:90991) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

With 1.0.6 it works fine.  It seems to be caused by #28.

I'm using Yarn, the packages `pug` and `pug-plain-loader` are in my devDependencies.

**Comment by KaelWD** [comment]
What version of pug do you have installed? Can you try deleting node_modules and running `yarn` again?

**Comment by ledermann** [comment]
... and here is my webpack config (I'm using [rails/webpacker](/rails/webpacker)).

<details>
<summary>environment.js</summary>

```javascript
const {
  environment
} = require('@rails/webpacker')
const {
  VueLoaderPlugin
} = require('vue-loader')
const vue = require('./loaders/vue')

const path = require('path')
environment.config.merge({
  resolve: {
    alias: {
      '@': path.resolve('app/javascript'),
      vue$: 'vue/dist/vue.runtime.esm.js',
      vuex$: 'vuex/dist/vuex.esm.js'
    }
  }
})

const isProduction = process.env.NODE_ENV === 'production'
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')
environment.plugins.append('VuetifyLoaderPlugin', new VuetifyLoaderPlugin())

environment.loaders.append('stylus', {
  test: /\.styl$/,
  use: [
    isProduction ? MiniCssExtractPlugin.loader : 'style-loader',
    'css-loader',
    'stylus-loader'
  ],
})

environment.loaders.append('pug', {
  test: /\.pug$/,
  use: ['pug-plain-loader']
})

environment.loaders.append('less', {
  test: /\.less$/,
  use: [
    isProduction ? MiniCssExtractPlugin.loader : 'style-loader',
    'css-loader',
    'less-loader'
  ],
})

environment.plugins.append('VueLoaderPlugin', new VueLoaderPlugin())
environment.loaders.append('vue', vue)

module.exports = environment
```
</details>

**Comment by WOo0W** [comment]
Same issue. After setting the version of `vuetify-loader` to 1.0.6, it works again.

**Comment by MatthewAry** [comment]
Guess we just have to roll things back.

**Comment by KaelWD** [comment]
Sorry, this slipped under my radar. I'll try to remember to look at it sometime over the weekend.
