### ISSUE TITLE
[VuetifyLoaderPlugin Error] No matching rule for vue-loader found.

### ISSUE THREAD

**Issue by throrin19** [vuetifyjs/vuetify-loader#87]
Hello, I use POIjs to load my VueJS project and I want to try the vuetifyLoader after my migration to Vuetify 2.

The problem is, when I use the plugin, I have this error : 

```
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (/manager-app/node_modules/vuetify-loader/lib/plugin.js:18:13)
    at webpack (/manager-app/node_modules/webpack/lib/webpack.js:51:13)
    at PoiCore.createWebpackCompiler (/manager-app/node_modules/poi/lib/index.js:466:40)
    at CAC.command.action (/manager-app/node_modules/poi/lib/plugins/serve.js:51:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

After research, POI use the vue-loader but with the absolute path of the loader : https://github.com/egoist/poi/blob/master/core/poi/lib/plugins/config-vue.js

Is it possible to take this case in charge?

Thanks

**Comment by DRoet** [comment]
`@vue/cli v4.1.0-beta.0` now also returns the full absolute path instead of just a string, opened up https://github.com/vuetifyjs/vuetify-loader/pull/97 with a simple fix

**Comment by schagdeh** [comment]
faced the same issue and npm install has solved mine.
